# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 681)
        MainWindow.setStyleSheet("QMainWindow{\n"
" \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(521, 511))
        self.groupBox.setMaximumSize(QtCore.QSize(521, 511))
        self.groupBox.setStyleSheet("QGroupBox{\n"
" background-color: white;\n"
" border-radius: 15px;\n"
" border: 2px  ridge gray;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 280, 70))
        self.label_2.setMinimumSize(QtCore.QSize(280, 70))
        self.label_2.setMaximumSize(QtCore.QSize(280, 70))
        self.label_2.setStyleSheet("image: url(:/newPrefix/logoPhoto.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logoPhoto.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_6.setGeometry(QtCore.QRect(0, 190, 521, 81))
        self.frame_6.setMinimumSize(QtCore.QSize(521, 81))
        self.frame_6.setMaximumSize(QtCore.QSize(521, 81))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setIndent(30)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 40, 460, 40))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(460, 40))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(460, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
" padding: 10px;\n"
" border: 1px solid;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
" border: 1px solid rgb(50, 50, 50);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
" border: 2px ridge rgb(50, 50, 50);\n"
"}")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame_5 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_5.setGeometry(QtCore.QRect(0, 270, 521, 120))
        self.frame_5.setMinimumSize(QtCore.QSize(521, 120))
        self.frame_5.setMaximumSize(QtCore.QSize(521, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setIndent(30)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 40, 460, 40))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(460, 40))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(460, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
" padding: 10px;\n"
" border: 1px solid;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
" border: 1px solid rgb(50, 50, 50);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
" border: 2px ridge rgb(50, 50, 50);\n"
"}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame = QtWidgets.QFrame(parent=self.groupBox)
        self.frame.setGeometry(QtCore.QRect(0, 130, 521, 60))
        self.frame.setMinimumSize(QtCore.QSize(521, 60))
        self.frame.setMaximumSize(QtCore.QSize(521, 60))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 45, 461, 31))
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(0, 390, 521, 121))
        self.frame_2.setMinimumSize(QtCore.QSize(521, 121))
        self.frame_2.setMaximumSize(QtCore.QSize(521, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 0, 460, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(460, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Log In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
