# Form implementation generated from reading ui file 'main_menu_user.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 550)
        MainWindow.setMinimumSize(QtCore.QSize(400, 550))
        MainWindow.setStyleSheet("QMainWindow{\n"
" \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainFrame.setMinimumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setBold(False)
        self.mainFrame.setFont(font)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameLeft = QtWidgets.QFrame(parent=self.mainFrame)
        self.frameLeft.setMinimumSize(QtCore.QSize(280, 500))
        self.frameLeft.setMaximumSize(QtCore.QSize(310, 16777215))
        self.frameLeft.setStyleSheet("")
        self.frameLeft.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameLeft)
        self.verticalLayout_4.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameTopLeft = QtWidgets.QFrame(parent=self.frameLeft)
        self.frameTopLeft.setMinimumSize(QtCore.QSize(0, 100))
        self.frameTopLeft.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frameTopLeft.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTopLeft.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTopLeft.setObjectName("frameTopLeft")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTopLeft)
        self.verticalLayout_5.setContentsMargins(-1, 15, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelLogo = QtWidgets.QLabel(parent=self.frameTopLeft)
        self.labelLogo.setMinimumSize(QtCore.QSize(221, 61))
        self.labelLogo.setMaximumSize(QtCore.QSize(221, 61))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("logoPhoto.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_5.addWidget(self.labelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frameTopLeft)
        self.frameMenu = QtWidgets.QFrame(parent=self.frameLeft)
        self.frameMenu.setMinimumSize(QtCore.QSize(221, 330))
        self.frameMenu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMenu.setObjectName("frameMenu")
        self.pushButtonInterviews = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonInterviews.setGeometry(QtCore.QRect(10, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonInterviews.setFont(font)
        self.pushButtonInterviews.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonInterviews.setObjectName("pushButtonInterviews")
        self.pushButtonApplications = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonApplications.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonApplications.setFont(font)
        self.pushButtonApplications.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonApplications.setObjectName("pushButtonApplications")
        self.pushButtonMentorMeetings = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonMentorMeetings.setGeometry(QtCore.QRect(10, 110, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonMentorMeetings.setFont(font)
        self.pushButtonMentorMeetings.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonMentorMeetings.setObjectName("pushButtonMentorMeetings")
        self.label = QtWidgets.QLabel(parent=self.frameMenu)
        self.label.setGeometry(QtCore.QRect(10, 0, 191, 31))
        self.label.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(70,70,70);\n"
"letter-spacing: 0.2em;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.frameMenu)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.frameLeftBottom = QtWidgets.QFrame(parent=self.frameLeft)
        self.frameLeftBottom.setMinimumSize(QtCore.QSize(0, 45))
        self.frameLeftBottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameLeftBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameLeftBottom.setObjectName("frameLeftBottom")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frameLeftBottom)
        self.pushButtonExit.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.pushButtonExit.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
" background-color: rgb(148, 0, 0);\n"
" color: rgb(255, 255, 255);\n"
" border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgba(157, 9, 19,200);\n"
"  color: rgb(255, 255, 255);\n"
"  border-radius: 10px;\n"
"  border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: white;\n"
"  color: rgb(170, 0, 0);\n"
"  border: 1px solid black;\n"
"}\n"
"\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_4.addWidget(self.frameLeftBottom)
        self.horizontalLayout_2.addWidget(self.frameLeft)
        self.frameRight = QtWidgets.QFrame(parent=self.mainFrame)
        self.frameRight.setMinimumSize(QtCore.QSize(0, 0))
        self.frameRight.setStyleSheet("background-color: white;")
        self.frameRight.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameRight.setObjectName("frameRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameRight)
        self.verticalLayout.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addWidget(self.frameRight)
        self.verticalLayout_2.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonInterviews.setText(_translate("MainWindow", "Interviews"))
        self.pushButtonApplications.setText(_translate("MainWindow", " Applications"))
        self.pushButtonMentorMeetings.setText(_translate("MainWindow", "Mentor Meetings"))
        self.label.setText(_translate("MainWindow", "MAIN MENU"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
