# Form implementation generated from reading ui file 'mentor_interview_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mentor_interviews_page_MainWindow(object):
    def setupUi(self, mentor_interviews_page_MainWindow):
        mentor_interviews_page_MainWindow.setObjectName("mentor_interviews_page_MainWindow")
        mentor_interviews_page_MainWindow.resize(1100, 750)
        mentor_interviews_page_MainWindow.setMinimumSize(QtCore.QSize(1100, 750))
        mentor_interviews_page_MainWindow.setMaximumSize(QtCore.QSize(1100, 750))
        self.centralwidget = QtWidgets.QWidget(parent=mentor_interviews_page_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 1050, 700))
        self.frame.setMinimumSize(QtCore.QSize(1050, 700))
        self.frame.setMaximumSize(QtCore.QSize(1050, 700))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Werhere_imaj_label = QtWidgets.QLabel(parent=self.frame)
        self.Werhere_imaj_label.setGeometry(QtCore.QRect(13, 0, 441, 111))
        self.Werhere_imaj_label.setText("")
        self.Werhere_imaj_label.setPixmap(QtGui.QPixmap("werhere_image.png"))
        self.Werhere_imaj_label.setObjectName("Werhere_imaj_label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(600, 0, 441, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("werhere_image.png"))
        self.label_2.setObjectName("label_2")
        self.All_Interviews_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.All_Interviews_pushButton.setGeometry(QtCore.QRect(13, 140, 281, 51))
        self.All_Interviews_pushButton.setStyleSheet("QPushButton:hover {\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }")
        self.All_Interviews_pushButton.setObjectName("All_Interviews_pushButton")
        self.Search_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.Search_pushButton.setGeometry(QtCore.QRect(970, 150, 71, 51))
        self.Search_pushButton.setStyleSheet("QPushButton:hover {\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }")
        self.Search_pushButton.setObjectName("Search_pushButton")
        self.Preferences_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.Preferences_pushButton.setGeometry(QtCore.QRect(13, 200, 201, 51))
        self.Preferences_pushButton.setStyleSheet("QPushButton:hover {\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }")
        self.Preferences_pushButton.setObjectName("Preferences_pushButton")
        self.Exit_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.Exit_pushButton.setGeometry(QtCore.QRect(13, 250, 71, 51))
        self.Exit_pushButton.setStyleSheet("QPushButton:hover {\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }")
        self.Exit_pushButton.setObjectName("Exit_pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(470, 150, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QTextEdit:hover {\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }\n"
"QTextEdit:pressed {\n"
"                    background-color: rgb(255, 255, 255);\n"
"                    color: rgb(0, 0, 255);\n"
"                    }")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setGeometry(QtCore.QRect(450, 230, 591, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(13, 310, 1021, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.Mentormenu_label = QtWidgets.QLabel(parent=self.frame)
        self.Mentormenu_label.setGeometry(QtCore.QRect(400, 40, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.Mentormenu_label.setFont(font)
        self.Mentormenu_label.setObjectName("Mentormenu_label")
        mentor_interviews_page_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mentor_interviews_page_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 29))
        self.menubar.setObjectName("menubar")
        mentor_interviews_page_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mentor_interviews_page_MainWindow)
        self.statusbar.setObjectName("statusbar")
        mentor_interviews_page_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mentor_interviews_page_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(mentor_interviews_page_MainWindow)
        
        self.Exit_pushButton.clicked.connect(self.Exit_clicked)
        self.All_Interviews_pushButton.clicked.connect(self.All_Interviews_clicked)
        self.Search_pushButton.clicked.connect(self.Search_clicked)
        self.Preferences_pushButton.clicked.connect(self.Preferences_clicked)

    def retranslateUi(self, mentor_interviews_page_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        mentor_interviews_page_MainWindow.setWindowTitle(_translate("mentor_interviews_page_MainWindow", "Mentor Menu "))
        self.All_Interviews_pushButton.setText(_translate("mentor_interviews_page_MainWindow", "All Interviews"))
        self.Search_pushButton.setText(_translate("mentor_interviews_page_MainWindow", "Search"))
        self.Preferences_pushButton.setText(_translate("mentor_interviews_page_MainWindow", "Preferences"))
        self.Exit_pushButton.setText(_translate("mentor_interviews_page_MainWindow", "Exit"))
        self.comboBox.setItemText(0, _translate("mentor_interviews_page_MainWindow", "Vit projesinin tamamina katilmasi uygundur"))
        self.comboBox.setItemText(1, _translate("mentor_interviews_page_MainWindow", "Vit projesinin ilk IT egitimi alanina yonlendirilmesi uygun olur"))
        self.comboBox.setItemText(2, _translate("mentor_interviews_page_MainWindow", "Vit projesi ingilizce egitimi alanina yonlendirilmesi uygundur"))
        self.comboBox.setItemText(3, _translate("mentor_interviews_page_MainWindow", "Vit projesi kapsaminda direk ise yonlendirilmesi uygundur"))
        self.comboBox.setItemText(4, _translate("mentor_interviews_page_MainWindow", "Direkt bireysel kocluk ile ise yonlendirilmesi uygun olur"))
        self.comboBox.setItemText(5, _translate("mentor_interviews_page_MainWindow", "Bir sonraki vit projesine katilmasi daha uygundur"))
        self.comboBox.setItemText(6, _translate("mentor_interviews_page_MainWindow", "Baska bir sektore yonlendirilmesi uygundur"))
        self.comboBox.setItemText(7, _translate("mentor_interviews_page_MainWindow", "Diger"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mentor_interviews_page_MainWindow", "Interview Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mentor_interviews_page_MainWindow", "Name-Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mentor_interviews_page_MainWindow", "Mentor"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mentor_interviews_page_MainWindow", "IT Knowledge"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mentor_interviews_page_MainWindow", "Density"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mentor_interviews_page_MainWindow", "Commends"))
        self.Mentormenu_label.setText(_translate("mentor_interviews_page_MainWindow", "                  Mentor Menu"))

 #Transitions and explainations

    def Exit_clicked(self):
        from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton
        QApplication.instance().quit()  

    def Preferences_clicked(self):
        from preference_admin_menu import Ui_admin_pref_men_MainWindow
        self.MainWindow= QtWidgets.QMainWindow()
        self.ui =Ui_admin_pref_men_MainWindow()
        self.ui.setupUi(mentor_interviews_page_MainWindow) 

    def All_Interviews_clicked(self):
        print("Now you are looking at All_Interviews")

    def Search_clicked(self):
        print("Now you are looking at Search")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mentor_interviews_page_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_mentor_interviews_page_MainWindow()
    ui.setupUi(mentor_interviews_page_MainWindow)
    mentor_interviews_page_MainWindow.show()
    sys.exit(app.exec())
